### ISSUE TITLE
add starter kanji lists for GENKI

### ISSUE THREAD

**Issue by Maxhodges** [white-rabbit-japan/white-rabbit-press-kanji-finder-2#2]
Lesson #; kanji list

3	一二三四五六七八九十百千万円時
7	京子小会社父母高校毎語文帰入
10	住正年売買町長道雪立自夜朝持
16	供世界全部始週以考開屋方運動教室
21	信経台風犬重初若送幸計遅配弟妹
9	午後前名白雨書友間家話少古知来
8	員新聞作仕事電車休言読思次何
5	山川元気天私今田女男見行食飲
14	彼代留族親切英店去急乗当音楽医者
11	手紙好近明病院映画歌市所勉強有旅
4	日本人月火水木金土曜上下中半
12	昔々神早起牛使働連別度赤青色
19	春秋冬花様不姉兄漢卒工研究質問多
6	東西南北口出右左分先生大学外国
17	歳習主結婚集発表品字活写真歩野
15	死意味注夏魚寺広転借走建地場足通
13	物鳥料理特安飯肉悪体空港着同海昼
20	皿声茶止枚両無払心笑絶対痛最続
18	目的力洋服堂授業試験貸図館終宿題
22	記銀回夕黒用守末待残番駅説案内忘
23	顔情怒変相横比化違悲調査果感答

**Comment by nick-gudumac** [comment]
Added in csv file!
